//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Altas
    {
        public int Id { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public int MontoPagar { get; set; }
    
        public virtual Ingresos Ingreso { get; set; }
    }
}
