//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public int PacientesId { get; set; }
        public int MedicosId { get; set; }
    
        public virtual Pacientes Paciente { get; set; }
        public virtual Medicos Medico { get; set; }
    }
}
